config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('intro.urls')),
    path('intro/', include('intro.urls')),
    path('subOutput/', include('intro.urls')),
    path('calendar/', include('intro.urls')),
    path('koldProject/', include('intro.urls')),
    path('proejectDetail/', include('intro.urls')),
    path('project/', include('project.urls')),
    path('dreamnetwork/', include('keywordList.urls')),
    path('dreamnetwork/list/', include('dream_list.urls')),
    path('webzine/', include('webzine.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'intro.views.page_not_found'

dream_list/urls.py
from django.urls import path
from . import views

app_name = 'dream_list'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.board_create, name='board_create'),
    path('edit/<int:id>/', views.to_edit_form, name='to_edit_form'),
    path('update/', views.board_update, name='board_update'),
    path('delete/<int:id>/', views.board_delete, name="board_delete")
]

intro/urls.py
from django.urls import path
from . import views

app_name = "intro"

urlpatterns = [
    path('', views.index, name='index'),
]

dream_list/models.py
from django.db import models
from django.conf import settings
from pytz import timezone

# Create your models here.
class Board(models.Model) :
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    password = models.CharField(max_length=20)
    cdate = models.DateTimeField()
    isVisible = models.CharField(max_length=10, default='true')

    @property
    def cdate_korean_time(self):
        korean_timezone = timezone(settings.TIME_ZONE)
        return self.cdate.astimezone(korean_timezone)

    def __str__ (self) :
        return self.title

dream_list/views.py
from dream_list.models import Board
from dream_list.form import BoardForm
from keywordList.models import Keyword
from keywordList.insert import KeywordInsert
from collections import Counter
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
from eunjeon import Mecab
# from konlpy.tag import Mecab


# Create your views here.
def index(request) :
    page = request.GET.get('page', 1) # page 이름으로 넘어오는 정보가 없으면 1
    query = request.GET.get('query')
    print('page : ', page)
    # 검색어
    if query :
        dream_list = Board.objects.filter(title__contains=query, isVisible='true').order_by('-id')
    else :
        dream_list = Board.objects.filter(isVisible='true').order_by('-id') # 정렬 순서를 cdate decending
    # 페이징 처리
    paginator=Paginator(dream_list, 10) # 페이징 기준을 10개 리스트로
    page_obj=paginator.get_page(page)
    print('page_obj', page_obj)
    context = {'dream_list' : page_obj }
    return render(request, 'dream_list/list.html', context)



def detail(request, id) :
    board = Board.objects.get(id=id)
    board.cdate = board.cdate.strftime('%Y년 %m월 %d일')
    context = {'board':board}
    return render(request, 'dream_list/board_detail.html', context)

def board_create(request) :
    mecab = Mecab()
    if request.method=='POST' :
        form=BoardForm(request.POST)
        if form.is_valid() :
            board=form.save(commit=False) # 저장은 하되 커밋은 하지 말 것.
            
            # 키워드 저장
            new_text = request.POST['content']
            # 명사 추출
            mecab_nouns = mecab.nouns(new_text)
            
            # 두 번 이상 쓰여진 키워드만 
            result = Counter(mecab_nouns)
            new_key = []
            for key, value in result.items() :
                if value > 1 :
                    new_key.append(key)
            # 한글자 제외        
            new_keywords = [word for word in new_key if len(word) > 1 ]
            all_key = Keyword.objects.all().values_list('word', flat=True) # 데이터베이스 전체 키워드
            all_key = list(all_key)
            # 이미 저장되어 있으면 제외
            for keyword in new_keywords :
                if keyword not in all_key :
                    Keyword(word=keyword).save()
            board.save()
            return redirect('dream_list:index')
    else :
        form=BoardForm()
    return render(request, 'dream_list/form.html', {'form':form})


def to_edit_form(request, id) :
    if request.method=='POST' :
        update_board = get_object_or_404(Board, id=id)
        update_form = BoardForm(instance=update_board)
        return render(request, 'dream_list/update_form.html', {'form':update_form, 'id':id})
    else :
        return redirect('dream_list:index')

def board_update(request) :
    if request.method=='POST' :
        id = request.POST['id']
        update_board = get_object_or_404(Board, id=id)
        update_form=BoardForm(request.POST, instance=update_board)
        if update_form.is_valid() :
            board=update_form.save(commit=False) 
            board.save()
            return redirect('dream_list:detail', id=id)
        else :
            return redirect('dream_list:index')
    else :
        return redirect('dream_list:index')


def board_delete(request, id) :
    if request.method=='POST' :
        board = get_object_or_404(Board, id=id)
        board.isVisible = 'false'
        board.save()
        return redirect('dream_list:index')
    else :
        return redirect('dream_list:index')

templates/dream_list/board_detail.html
{% extends 'base_dream.html' %} {% block content %}
<style>
  #main {
    z-index: 1;
  }

  #popEdit,
  #popDelete {
    z-index: 2;
    position: absolute;
    top: 10px;
    left: 0px;
    width: 100%;
    background-color: rgba(0, 0, 0, 0.8);
  }

  .close {
    z-index: 4;
  }
</style>
<div class="detail-container">
  <div class="text-box">
    <div class="dreams">
      <div class="dream-cdate">{{board.cdate}}</div>
      <br />
      <div class="dream-title">{{board.title}}</div>
      <br />
      <div class="dream-content">{{board.content|linebreaksbr}}</div>
    </div>
    <br />
    <br />
    <br />
    <div class="dream-user">
      <div class="dream-writer">{{board.writer}}</div>
      <br />
      <br />
      <div class="dream-btn">
        <button class="list-btn btn-update" onclick="editPop('open');">
          수정
        </button>
        <button class="list-btn btn-delete" onclick="deletePop('open');">
          삭제
        </button>
      </div>
    </div>
  </div>
</div>
<div id="popEdit" style="display: none">
  <div class="popup" style="vertical-align: middle">
    <input type="password" id="editpw" placeholder="비밀번호를 입력하세요" />
    <br />
    <form id="editForm">
      {% csrf_token %}
      <button id="editPost">
        <a
          href="javascript:"
          onclick="editPost({{board.id}});"
          style="color: #27272a !important"
          >일기 수정</a
        >
      </button>
      <button class="close-btn">
        <a
          href="javascript:"
          onClick="editPop('close');"
          style="color: #ffffff !important"
          >x</a
        >
      </button>
    </form>
  </div>
</div>
<div id="popDelete" style="display: none">
  <div class="popup">
    <input type="password" id="delpw" placeholder="비밀번호를 입력하세요" />
    <br />
    <form id="deleteForm">
      {% csrf_token %}
      <button id="deletePost">
        <a
          href="javascript:"
          onclick="deletePost({{board.id}});"
          style="color: #27272a !important"
          >일기 삭제</a
        >
      </button>
      <button class="close-btn">
        <a
          href="javascript:"
          onClick="deletePop('close');"
          style="color: #ffffff !important"
          >x</a
        >
      </button>
    </form>
  </div>
</div>
{% endblock %} {% block script %}
<script>
  function editPop(type) {
    if (type == "open") {
      $("#popEdit").attr("style", "display:inline");
      $("#popEdit").height($(document).height());
    } else if (type == "close") {
      $("#popEdit").attr("style", "display:none");
    }
  }

  function deletePop(type) {
    if (type == "open") {
      $("#popDelete").attr("style", "display:inline");
      $("#popDelete").height($(document).height());
    } else if (type == "close") {
      $("#popDelete").attr("style", "display:none");
    }
  }

  function editPost(id) {
    if ($("#editpw").val() == "{{board.password}}") {
      var editForm = $("#editForm");
      var url = "{% url 'dream_list:to_edit_form' board.id %}";
      editForm.attr("action", url);
      editForm.attr("method", "POST");
      editForm.submit();
    } else {
      alert("비밀번호가 맞지 않습니다.");
      window.location.reload();
    }
  }

  function deletePost(id) {
    if ($("#delpw").val() == "{{board.password}}") {
      var delform = $("#deleteForm");
      var url = "{% url 'dream_list:board_delete' board.id %}";
      delform.attr("action", url);
      delform.attr("method", "POST");
      delform.submit();
    } else {
      alert("비밀번호가 맞지 않습니다.");
      window.location.reload();
    }
  }

  $(document).ready(function () {});
</script>
{% endblock %}

templates/dream_list/form.html
{% extends 'base_dream.html' %} {% block content %}
<style>
  @media (max-width: 600px) {
    .headline {
      display: none;
    }
  }
</style>
<div class="form-container">
  <div class="form-content">
    <form method="post" class="post-form my-3">
      {% csrf_token %}
      <!-- 오류표시 Start -->
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %} {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }} {% endif %} {% endfor %}
      </div>
      {% endif %}
      <!-- 오류표시 End -->
      <div class="form-main">
        <span class="format-date">
          <input
            type="date"
            class="dream-form form-date"
            name="cdate"
            id="cdate"
            style="padding-top: 10px"
            required
          />
        </span>
        <input
          type="text"
          class="dream-form form-title"
          name="title"
          id="title"
          placeholder="제목"
          value="{{ form.title.value|default_if_none:'' }}"
          maxlength="30"
          required
        />
        <textarea
          class="dream-form form-contents"
          name="content"
          placeholder="내용"
          id="content"
          rows="10"
          required
        >
{{ form.content.value|default_if_none:'' }}</textarea
        >
      </div>
      <div class="form-footer">
        <div class="form-user-area">
          <input
            type="text"
            class="dream-form writer-name"
            name="writer"
            id="writer"
            placeholder="이름"
            value="{{ form.writer.value|default_if_none:'' }}"
            maxlength="10"
            required
          />
          <input
            type="password"
            class="dream-form writer-pw"
            name="password"
            id="password"
            placeholder="비밀번호"
            value="{{ form.password.value|default_if_none:'' }}"
            style="ime-mode: disabled"
            required
          />
        </div>
        <button type="submit" class="form-btn">올리기</button>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block script %}
<script>
  $(document).ready(function () {
    curr = new Date();
    utc = curr.getTime() + curr.getTimezoneOffset() * 60 * 1000;
    const KR_TIME_DIFF = 9 * 60 * 60 * 1000; // UTC에서 9시간 추가
    kr_curr = new Date(utc + KR_TIME_DIFF);
    console.log(kr_curr.toISOString().slice(0, 10));

    document.getElementById("cdate").value = kr_curr.toISOString().slice(0, 10);
  });
</script>
{% endblock%}

templates/dream_list/list.html
{% extends 'base_dream.html' %}
{% if messages %}
    {% for message in messages %}
    <script>
        alert('{{message.message}}');
    </script>
    {% endfor %}
{% endif %}
{% load list_filter %}
{% load static %}
{% block content %}
<style>
@media (max-width: 600px) {
    .btn-basic {top:100px; width:100vw;}
}
</style>
<div class="list-container">
    <div class="btn-basic list-on-list">
        <img class="btn-list-over" src="{% static 'images/List.png'%}">
        List
    </div>
    <div class="btn-basic" style="text-align:center; height:80px;">
        <a href="{% url 'dream_list:board_create' %}" class="btn-write" style="color:#000000;">
            <img class="btn-write-out" src="{% static 'images/pencil.png'%}">
            Write
        </a>
    </div>  
    <br>
    <table class="table table-hover table-sm">
        <tbody>
        {% if dream_list %}
        {% for board in dream_list %}
        <tr class="text-center">
            <!--<td>{{ dream_list.paginator.count|sub:dream_list.start_index|sub:forloop.counter0|add:1 }}</td>-->
            <td class="text-left">
                <a href="{% url 'dream_list:detail' board.id %}" style="color:#000000;">{{ board.title }}</a>                
            </td>
            <td>{{ board.writer }}</td>            
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center" style="font-size: 24px; color: #303030; border:none !important;">
        <!-- 이전페이지 -->
        {% if dream_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ dream_list.previous_page_number }}" href="/dreamnetwork/list/?page={{ dream_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="/dreamnetwork/list/#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in dream_list.paginator.page_range %}
        {% if page_number >= dream_list.number|add:-1 and page_number <= dream_list.number|add:4 %}
            {% if page_number == dream_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="/dreamnetwork/list/?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="/dreamnetwork/list/?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if dream_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ dream_list.next_page_number }}" href="/dreamnetwork/list/?page={{ dream_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="/dreamnetwork/list/#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<div class="list-search-and-page">
<form id="pageForm" method="get" action="{% url 'dream_list:index' %}">    
    <input type="hidden" id="page" name="page" value="{{ page }}">  
</form>


<form id="searchForm" method="get" action="{% url 'dream_list:index' %}">    
    <input type="text" id="query" name="query">
    <input type="submit" class="list-btn" value="검색">
</form>
</div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#pageForm").submit();
        });     
    });
</script>
{% endblock %}

templates/dream_list/update_form.html
{% extends 'base_dream.html' %}
{% block content %}
<style>
@media (max-width: 600px) {
    .headline {display:none;}
}
</style>
<div class="form-container">
    <div class="form-content">
    <form method="post" class="post-form my-3" action="{% url 'dream_list:board_update' %}">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <span>
        <input type="hidden" name="id" value="{{ id }}">
        <input type="date" class="dream-form form-date" name="cdate" id="cdate" required>
        </span class="format-date">
        <input type="text" class="dream-form form-title" name="title" id="title" placeholder="제목"
                   value="{{ form.title.value|default_if_none:'' }}" required>
        <textarea class="dream-form form-contents" name="content" placeholder="내용"
                      id="content" rows="10" required>{{ form.content.value|default_if_none:'' }}</textarea>
                      
        <div class="form-footer">
        <div class="form-user-area">
        <input type="text" class="dream-form writer-name" name="writer" id="writer" placeholder="이름"
                   value="{{ form.writer.value|default_if_none:'' }}" maxlength='10' required>
        <input type="password" class="dream-form writer-pw" name="password" id="password" placeholder="비밀번호"
                   value="{{ form.password.value|default_if_none:'' }}" style="ime-mode:disabled;" required>
        </div>
        <button type="submit" class="form-btn">올리기</button>
        </div>
    </form>
    </div>
</div>
{% endblock %}
{% block script %}
<script>

$(document).ready(function(){
    curr = new Date();
    utc = curr.getTime() + (curr.getTimezoneOffset() * 60 * 1000);
    const KR_TIME_DIFF = 9 * 60 * 60 * 1000;  // UTC에서 9시간 추가
    kr_curr = new Date(utc + (KR_TIME_DIFF));    
    console.log(kr_curr.toISOString().slice(0,10));
     
    document.getElementById('cdate').value = kr_curr.toISOString().slice(0,10);
});

</script>
{% endblock%}