config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('intro.urls')),
    path('intro/', include('intro.urls')),
    path('subOutput/', include('intro.urls')),
    path('calendar/', include('intro.urls')),
    path('koldProject/', include('intro.urls')),
    path('proejectDetail/', include('intro.urls')),
    path('project/', include('project.urls')),
    path('dreamnetwork/', include('keywordList.urls')),
    path('dreamnetwork/list/', include('dream_list.urls')),
    path('webzine/', include('webzine.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'intro.views.page_not_found'

dream_list/urls.py
from django.urls import path
from . import views

app_name = 'dream_list'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.board_create, name='board_create'),
    path('edit/<int:id>/', views.to_edit_form, name='to_edit_form'),
    path('update/', views.board_update, name='board_update'),
    path('delete/<int:id>/', views.board_delete, name="board_delete")
]

intro/urls.py
from django.urls import path
from . import views

app_name = "intro"

urlpatterns = [
    path('', views.index, name='index'),
]

keywordList/urls.py
from django.urls import path
from . import views

app_name = 'keywordList'

urlpatterns = [
    path('', views.keylist, name='keylist'),
    path('result/<str:word>/', views.result, name="result")
]

keywordList/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model) :
    word = models.CharField(max_length=10)
    def __str__ (self) :
        return self.word

keywordList/views.py
from keywordList.models import Keyword
from dream_list.models import Board
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

# Create your views here.
def keylist(request) :
    keyword_list = Keyword.objects.order_by('word')
    context = { 'key_list' : keyword_list}
    return render(request, 'keyword_list/key.html', context)


def result(request, word) :
    key_list = Board.objects.filter(content__contains=word).order_by('-id')

    context = {'key_list' : key_list, 'word' : word }
    return render(request, 'keyword_list/result.html', context)

templates/keyword_list/key.html
{% extends 'base_dream.html' %} {% block content %} {% load static %}
<style>
  body {
    background: #000000;
  }
  .head-title {
    color: #ffffff;
  }
</style>

<div class="btn-area">
  <div class="btn-basic btn-right-line btn-basic-list basic-list-out">
    <a
      href="{% url 'dream_list:index' %}"
      class="btn-list"
      style="color: #ffffff"
    >
      <img class="btn-list-over" src="{% static 'images/List-white.svg'%}" />
      List
    </a>
  </div>
  <div
    class="btn-basic btn-right-line btn-basic-write basic-write-over"
    style="display: none"
  >
    <a
      href="{% url 'dream_list:board_create' %}"
      class="btn-write"
      style="color: #000000"
    >
      <img class="btn-write-out" src="{% static 'images/pencil.svg'%}" />
      Write
    </a>
  </div>
  <div
    class="btn-basic btn-left-line btn-basic-list basic-list-over"
    style="display: none"
  >
    <a
      href="{% url 'dream_list:index' %}"
      class="btn-list"
      style="color: #000000"
    >
      <img class="btn-list-out" src="{% static 'images/List.svg'%}" />
      List
    </a>
  </div>
  <div class="btn-basic btn-left-line btn-basic-write basic-write-out">
    <a
      href="{% url 'dream_list:board_create' %}"
      class="btn-write"
      style="color: #ffffff"
    >
      <img class="btn-write-over" src="{% static 'images/pencil-white.svg'%}" />
      Write
    </a>
  </div>
</div>
<div class="container-box">
  <div class="door-area" onmouseover="doormouseover();" onmouseout="doormouseout();">
    <table class="keywords-in-the-door" style="table-layout: fixed">
      {% if key_list %} 
        {% for key in key_list %} 
          {% if forloop.counter0|divisibleby:7 %}
          <tr>
          {% endif %}
          <td style="font-size: 18px; padding-bottom: 17px !important; white-space: nowrap;">
          <a class="key-link" style="color: #000000" href="{% url 'keywordList:result' key.word %}">{{key.word}}</a>
          </td>
          {% if forloop.counter|divisibleby:7 %}
          </tr>
          {% endif %} 
        {% endfor %} 
      {% endif %}
    </table>
  </div>
</div>

{% endblock %} {% block script %}
<script type="text/javascript">
  function doormouseover() {
    $("body").css("color", "black");
    $("body").css("backgroundColor", "white");
    $(".door-area").css(
      "background",
      "linear-gradient(180deg, #FFFFFF 0%, rgba(0, 0, 0, 0) 15.44%), linear-gradient(0deg, #000000, #000000)"
    );
    $(".door-area").css("box-shadow", "0px 4px 80px #000000");
    $(".head-title").css("color", "#000000");
    $(".basic-list-out").css("display", "none");
    $(".basic-list-over").css("display", "inline");
    $(".basic-write-out").css("display", "none");
    $(".basic-write-over").css("display", "inline");
    $(".btn-list").css("color", "#000000");
    $(".btn-write").css("color", "#000000");
    $(".key-link").css("color", "#FFFFFF");
  }

  function doormouseout() {
    $("body").css("color", "white");
    $("body").css("backgroundColor", "black");
    $(".door-area").css(
      "background",
      "linear-gradient(180deg, #000000 0%, rgba(0, 0, 0, 0) 15.44%), linear-gradient(0deg, #FFFFFF, #FFFFFF)"
    );
    $(".head-title").css("color", "#FFFFFF");
    $(".basic-list-out").css("display", "inline");
    $(".basic-list-over").css("display", "none");
    $(".basic-write-out").css("display", "inline");
    $(".basic-write-over").css("display", "none");
    $(".btn-list").css("color", "#FFFFFF");
    $(".btn-write").css("color", "#FFFFFF");
    $(".key-link").css("color", "#000000");
  }

  // 모바일 감지 이벤트
  function Mobile() {
    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
      navigator.userAgent
    );
  }

  $(document).ready(function () {
    if (Mobile()) {
      var tble = "";
    }
  });
</script>
{% endblock %}

templates/keyword_list/result.html
{% extends 'base_dream.html' %}
{% block content %}

<div class="list-container" style="top: 100px;">
    <div class="btn-basic" style="text-align:center; height:80px;">
        {% if word %}
            {{word}}
        {% endif %}
    </div>  
    <br>
    <table class="table table-hover table-sm">
        <tbody>
        {% if key_list %}
        {% for board in key_list %}
        <tr class="text-center">
            <td class="text-left">
                <a href="{% url 'dream_list:detail' board.id %}" style="color:#000000;">{{ board.title }}</a>                
            </td>
            <td>{{ board.writer }}</td>            
            <td>{{ board.cdate|date:"y/m/d" }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    </div>
</div>
{% endblock %}